FROM php:5-jessie

RUN apt update \
    && apt install \
       zlib1g-dev libicu-dev \
       mysql-client \
       wget zip libmcrypt-dev \
       gnupg python-pip libyaml-dev \
       -y \
    && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt install -y nodejs \
    && apt-get clean && apt-get autoclean && apt-get autoremove --purge -y \
    && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/* \
    && pecl install intl \
    && docker-php-ext-configure intl \
    && docker-php-ext-install -j$(nproc) pcntl intl calendar mysql mysqli mcrypt \
    && echo "date.timezone = \"Europe/Paris\"" >> /usr/local/etc/php/php.ini \
    && echo "display_errors = On" >> /usr/local/etc/php/php.ini \
    && echo "display_startup_errors = On" >> /usr/local/etc/php/php.ini \
    && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
    pip install awscli

# Add and decompress local file to /tmp. Zend will not change so why download at every build ?
ADD lib/ZendFramework-1.12.20.tar.gz /tmp/
RUN mkdir -p /usr/share/php && mv /tmp/ZendFramework-1.12.20/library/Zend /usr/local/lib/php/Zend && rm -rf /tmp/*

# Use https://github.com/vishnubob/wait-for-it
ADD lib/wait-for-it.sh /opt/
