FROM php:5

RUN apt update \
    && apt install \
       zlib1g-dev libicu-dev \
       mysql-client mysql-client-5.5 \
       wget zip libmcrypt-dev \
       -y \
    && apt-get clean && apt-get autoclean && apt-get autoremove --purge -y \
    && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

RUN pecl install intl

RUN docker-php-ext-configure intl && \
    docker-php-ext-install -j$(nproc) pcntl intl calendar mysql mysqli mcrypt && \
    echo "date.timezone = \"Europe/Paris\"" >> /usr/local/etc/php/php.ini && \
    echo "display_errors = On" >> /usr/local/etc/php/php.ini && \
    echo "display_startup_errors = On" >> /usr/local/etc/php/php.ini

# RUN pecl install xdebug-2.5.5
# RUN docker-php-ext-enable xdebug

# /usr/share/php doesn't exist anymore ... Without that it will silently fail :(
RUN mkdir -p /usr/share/php

# Add and decompress local file to /tmp. Zend will not change so why download at every build ?
ADD lib/ZendFramework-1.12.20.tar.gz /tmp/
RUN mv /tmp/ZendFramework-1.12.20/library/Zend /usr/local/lib/php/Zend && rm -rf /tmp/*

# Use https://github.com/vishnubob/wait-for-it
ADD lib/wait-for-it.sh /opt/
