FROM php:5-jessie

RUN apt update \
    && apt install \
       zlib1g-dev libicu-dev \
       mysql-client \
       wget zip libmcrypt-dev \
       git \
       -y \
    && apt-get clean && apt-get autoclean && apt-get autoremove --purge -y \
    && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/* \
    && pecl install intl \
    && docker-php-ext-configure intl \
    && docker-php-ext-install -j$(nproc) pcntl intl calendar mysql mysqli mcrypt pdo pdo_mysql \
    && echo "date.timezone = \"Europe/Paris\"" >> /usr/local/etc/php/php.ini \
    && echo "display_errors = On" >> /usr/local/etc/php/php.ini \
    && echo "display_startup_errors = On" >> /usr/local/etc/php/php.ini

# Add and decompress local file to /tmp. Zend will not change so why download at every build ?
ADD lib/ZendFramework-1.12.20.tar.gz /tmp/
RUN mkdir -p /usr/share/php && mv /tmp/ZendFramework-1.12.20/library/Zend /usr/local/lib/php/Zend && rm -rf /tmp/*

# Use https://github.com/vishnubob/wait-for-it
ADD lib/wait-for-it.sh /opt/
